/**
 * @fileoverview gRPC-Web generated client stub for user
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: src/proto/user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_user_pb from '../../src/proto/user_pb'; // proto import: "src/proto/user.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetUsers = new grpcWeb.MethodDescriptor(
    '/user.UserService/GetUsers',
    grpcWeb.MethodType.UNARY,
    src_proto_user_pb.GetUsersRequest,
    src_proto_user_pb.GetUsersResponse,
    (request: src_proto_user_pb.GetUsersRequest) => {
      return request.serializeBinary();
    },
    src_proto_user_pb.GetUsersResponse.deserializeBinary
  );

  getUsers(
    request: src_proto_user_pb.GetUsersRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_user_pb.GetUsersResponse>;

  getUsers(
    request: src_proto_user_pb.GetUsersRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.GetUsersResponse) => void): grpcWeb.ClientReadableStream<src_proto_user_pb.GetUsersResponse>;

  getUsers(
    request: src_proto_user_pb.GetUsersRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.GetUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/GetUsers',
        request,
        metadata || {},
        this.methodDescriptorGetUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/GetUsers',
    request,
    metadata || {},
    this.methodDescriptorGetUsers);
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    src_proto_user_pb.GetUserRequest,
    src_proto_user_pb.GetUserResponse,
    (request: src_proto_user_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    src_proto_user_pb.GetUserResponse.deserializeBinary
  );

  getUser(
    request: src_proto_user_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_user_pb.GetUserResponse>;

  getUser(
    request: src_proto_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.GetUserResponse) => void): grpcWeb.ClientReadableStream<src_proto_user_pb.GetUserResponse>;

  getUser(
    request: src_proto_user_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.GetUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    src_proto_user_pb.CreateUserRequest,
    src_proto_user_pb.CreateUserResponse,
    (request: src_proto_user_pb.CreateUserRequest) => {
      return request.serializeBinary();
    },
    src_proto_user_pb.CreateUserResponse.deserializeBinary
  );

  createUser(
    request: src_proto_user_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_user_pb.CreateUserResponse>;

  createUser(
    request: src_proto_user_pb.CreateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.CreateUserResponse) => void): grpcWeb.ClientReadableStream<src_proto_user_pb.CreateUserResponse>;

  createUser(
    request: src_proto_user_pb.CreateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.CreateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorUpdateUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/UpdateUser',
    grpcWeb.MethodType.UNARY,
    src_proto_user_pb.UpdateUserRequest,
    src_proto_user_pb.UpdateUserResponse,
    (request: src_proto_user_pb.UpdateUserRequest) => {
      return request.serializeBinary();
    },
    src_proto_user_pb.UpdateUserResponse.deserializeBinary
  );

  updateUser(
    request: src_proto_user_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_user_pb.UpdateUserResponse>;

  updateUser(
    request: src_proto_user_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.UpdateUserResponse) => void): grpcWeb.ClientReadableStream<src_proto_user_pb.UpdateUserResponse>;

  updateUser(
    request: src_proto_user_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.UpdateUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/UpdateUser',
        request,
        metadata || {},
        this.methodDescriptorUpdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/UpdateUser',
    request,
    metadata || {},
    this.methodDescriptorUpdateUser);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/DeleteUser',
    grpcWeb.MethodType.UNARY,
    src_proto_user_pb.DeleteUserRequest,
    src_proto_user_pb.DeleteUserResponse,
    (request: src_proto_user_pb.DeleteUserRequest) => {
      return request.serializeBinary();
    },
    src_proto_user_pb.DeleteUserResponse.deserializeBinary
  );

  deleteUser(
    request: src_proto_user_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_user_pb.DeleteUserResponse>;

  deleteUser(
    request: src_proto_user_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.DeleteUserResponse) => void): grpcWeb.ClientReadableStream<src_proto_user_pb.DeleteUserResponse>;

  deleteUser(
    request: src_proto_user_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_user_pb.DeleteUserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

}

